feat: add prettier to the project
CodersCampLittleDevs/CodersCamp2021-ProjectServerSideJavaScript-PetsAdoptAndCarePortal pull request #2
Opened 2022-02-20 20:49 UTC by MaciekPon

- add prettier configuration file

2022-02-20 21:08 UTC, ruljin requested changes
Changes requested

2022-02-20 21:08 UTC, ruljin commented on .prettierrc
> +  "bracketSpacing": true
Add `trailingComma`

2022-02-20 21:39 UTC, ruljin requested changes
Changes requested

2022-02-20 21:39 UTC, ruljin commented on .prettierrc
> +  "trailingComma": "es5"
Change to`all`

2022-02-20 21:52 UTC, alicjaguzik commented
LGTM

2022-02-21 07:08 UTC, JustD1d1t approved these changes
LGTM

2022-02-21 18:03 UTC, ruljin approved these changes

2022-02-21 18:03 UTC, merged