Njs 4 ".env file"
CodersCampLittleDevs/CodersCamp2021-ProjectServerSideJavaScript-PetsAdoptAndCarePortal pull request #3
Opened 2022-02-23 13:33 UTC by DawidZlobecki

2022-02-23 17:18 UTC, JustD1d1t commented on app/index.js
> +import {} from "dotenv/config";
import what?

2022-02-23 19:08 UTC, JustD1d1t approved these changes
LGTM

2022-02-24 11:07 UTC, ruljin requested changes
Changes requested

2022-02-24 11:07 UTC, ruljin commented on .env.example
> +DB_URL=LINK TO MONGODB
If in the example you add any values, it should be example values, defaults or no values. In this case example or no values wouls be good

2022-02-24 11:07 UTC, ruljin commented on app/index.js
> +dotenv.config();
Never, leave usage lines between imports. Move it beneath them

2022-02-24 11:09 UTC, ruljin commented
I can't comment `README.md` so I will do it here. Add table of contents and if you don't have any idea how to write this section, try basing on the `README.md` from the previous projects for example. The content should be more self-explenatory - what is `PORT` env used for? What secret for etc.

2022-02-24 20:50 UTC, ruljin commented
My proposition.

Section name: `Environment variables`
Content of the section: ".env file is a source of environment variables for this application"
"PORT - blah, blah, blah,"
"DB_URL - blah, blah, blah,"
"JWT_SECRET - blah, blah, blah".

That's the last thing to change IMO.

2022-03-07 19:03 UTC, merged